version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./Server
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./Server:/var/www/html
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: userpassword
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: weatherwise
        ports:
            - "3306:3306"
        command: --skip-ssl
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
          PMA_HOST: db
          PMA_USER: root
          PMA_PASSWORD: root
      ports:
          - 8080:80
    flyway:
      image: flyway/flyway 
      volumes:
        - ./.migrations:/flyway/sql
      depends_on:
        - db
      command:
        - -url=jdbc:mysql://db:3306/weatherwise?allowPublicKeyRetrieval=true&useSSL=false
        - -schemas=weatherwise
        - -user=root
        - -password=root
        - migrate

